### ISSUE TITLE
Av detection

### ISSUE THREAD

**Issue by tehseensagar** [xp4xbox/Puffader#30] opened 2018-01-29 08:25 UTC
I sort out the issue is Antivirus it is detecting the signature of binary which cause the following error

Insufficient system resources exist to complete the requested services

Can you please help me to fix this for binary , I've tried to add version , file description and name but didnot help .

Also diagnose an issue , once you turned off you internet process killed it self which is very strange. As I was expecting it will store the keylog data  in file once internet is restore or connected it will send file via email.

Regards

**Comment by xp4xbox** [comment] 2018-01-29 13:43
I cannot sign the binary since I would need to apply for one by Microsoft. Adding version, file description, etc, would not do anything to sign it. Currently the program has a 2/56 detection rate by antivirus which is pretty much the best you can get. Once I have some time I will add this feature.

**Comment by tehseensagar** [comment] 2018-01-30 06:24
@xp4xbox  thank you for your prompt response. But there is a bug which cause process to die when there is no internet available. Could you please fix that issue. AV bypass I will manage it .

Regards

**Comment by xp4xbox** [comment] 2018-01-30 17:11
Its not a bug, I made it that way. But I can improve it. I will do that sometime soon.

**Comment by tehseensagar** [comment] 2018-01-31 07:20
@xp4xbox  could you please share your linkedin / gmail / skype address.

Thanks 

Regards

**Comment by tehseensagar** [comment] 2018-01-31 08:42
@xp4xbox  could you please share your linkedin / gmail / skype address.

Thanks 

Regards

**Comment by xp4xbox** [comment] 2018-01-31 13:55
Why

**Comment by xp4xbox** [comment] 2018-01-31 18:50
Why do you want my email? Anyway I made an improvement just now, so the program will not exit if there is no internet.

**Comment by tehseensagar** [comment] 2018-02-02 07:21
@xp4xbox great well to share email or linkedin profile to be in touch with such a nice person so I may increase and share idea :). 

Regards

**Comment by xp4xbox** [comment] 2018-02-02 19:33
If you give me your email, I will send you my email.

edit: closing this for now, if you want to give me your email, just add a comment.

**Closed as completed** 2018-02-05 20:01 UTC
Labels: Help
